### PR TITLE
Removed leftover code from Git Merge Conflict

### PR DESCRIPTION
**Pull request by cjl032224**
I checked out your code.  Saw there was leftover Git Merge Conflict code.  I took care of that by creating a copy of the master branch, making the changes locally, added, committed and pushed the changes.  So my local copy became a remote copy here on github.  I've created a Pull Request.  This is where other developers look over the code changes and decide if the changes from the branch should be integrated and merged with the master branch.  This allows changes to go through vetting before merge.

### CODE REVIEW

**Review by cjl032224 — COMMENTED** [review]
I recommend approving and merging these changes.  They are minimal and don't touch formatting or functionality. Once merged with master, run 'git pull origin master' on your local branch to get the updated branch from the remote repo.

**Comment by Weston714** [comment]
This is Wes I will look at the code when I get home

**Comment by Squad32codes** [comment]
ok

**Comment by Weston714** [comment]
I think we fixed it bren was trying to work on some css but didn't know I added 2 linked files

**Comment by Weston714** [comment]
ok im going to merge it because there must have been some changes that are bad

**Comment by Weston714** [comment]
ok I just pushed can you check if there is any thing we should change

**Pull request merged**
